// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ4EkSHvXCPGISek7Na4f4GEpYPBvxaqA',
    appId: '1:142884686200:web:b36595b342afbbf125608d',
    messagingSenderId: '142884686200',
    projectId: 'fitdostbackend',
    authDomain: 'fitdostbackend.firebaseapp.com',
    storageBucket: 'fitdostbackend.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmZGzx9GgRE74Bv_OExPEHmIyGAXQHX2I',
    appId: '1:142884686200:android:8df7f8e10f5dbb6625608d',
    messagingSenderId: '142884686200',
    projectId: 'fitdostbackend',
    storageBucket: 'fitdostbackend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7JXhhu3RHpEQ4SJ_2NcIcTNwXQs3OaCE',
    appId: '1:142884686200:ios:b5e00d8fe13e3c0a25608d',
    messagingSenderId: '142884686200',
    projectId: 'fitdostbackend',
    storageBucket: 'fitdostbackend.appspot.com',
    iosBundleId: 'com.example.fitdostApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7JXhhu3RHpEQ4SJ_2NcIcTNwXQs3OaCE',
    appId: '1:142884686200:ios:b5e00d8fe13e3c0a25608d',
    messagingSenderId: '142884686200',
    projectId: 'fitdostbackend',
    storageBucket: 'fitdostbackend.appspot.com',
    iosBundleId: 'com.example.fitdostApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZ4EkSHvXCPGISek7Na4f4GEpYPBvxaqA',
    appId: '1:142884686200:web:985d04e268c5735d25608d',
    messagingSenderId: '142884686200',
    projectId: 'fitdostbackend',
    authDomain: 'fitdostbackend.firebaseapp.com',
    storageBucket: 'fitdostbackend.appspot.com',
  );
}
